---
- name: Install mysql server and dependencies packages
  yum: 
    name: "{{item}}" 
    state: installed
  with_items:
    - mysql-server
    - mysql
    - python3-PyMySQL
    - php-mysqlnd

- name: Start and enable Mysql Service
  systemd: 
    name: mysqld 
    state: started 
    enabled: yes

- name: permit traffic in default zone for mysql service 
  firewalld: 
    port: "{{ mysql_port }}" 
    permanent: yes 
    state: enabled 
  notify: 
  - reload service firewalld

- name: Create a database user
  mysql_user:
    name: demo
    password: demo
    priv: '*.*:ALL'
    host: localhost
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create a new database
  mysql_db:
    name: demo
    state: present
    collation: utf8_general_ci
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Copy sample data to managed host
  copy: 
    src: "{{ mysql_src }}" 
    dest: "{{ mysql_dest }}"

- name: Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: Restart Apache
  systemd:
    name: httpd
    state: restarted
    enabled: yes

- name: copy Hello World PHP script with database to the managed host
  copy: 
    src: "{{ php_page_mysql_src }}"
    dest: "{{ php_page_mysql_dest }}"
    mode: '0664'

- name: get status of success of launching php page
  ansible.builtin.shell: curl -i localhost 2>&1 | awk '/HTTP\// {print $2}' > /root/php_test

- name: get status of success of launching php page through my sql
  ansible.builtin.shell: curl -i localhost/db.php 2>&1 | awk '/HTTP\// {print $2}' > /root/php_through_mysql_test
  register: php_inside_mysql_test
